### ISSUE TITLE
How can I manage multiple projects?

### ISSUE THREAD

**Issue by slowcoder76** [oprogramador/vim-ftp#4]
How can I manage multiple projects?

SlowCoder76

**Comment by oprogramador** [comment]
For now, it seems that you have the following options:
- writing down the creds to all the servers in your `.vimrc` and commenting out the inactive ones, remember to restart vim after updating `.vimrc`
- having multiple vim config files, and starting vim with `vim -u ./path/to/your/vimrcfile`
- using separate physical machines or virtual machines or multiple installed OS on your hard drive

Anyway, I invite you to open a PR if you'd like another option like being able to switch easily projects dynamically in a given vim instance. I also invite you to star this repo, and to invite your friends to star it.

**Comment by oprogramador** [comment]
I close due to a lack of activity.
